# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Matplotlib Templates
author: Andreas Siemens
copyright: "Andreas Siemens 2023"
logo: logo/history-2.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  #execute_notebooks: force
  execute_notebooks: auto

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/Andreas-Siemens/matplotlib-templates.git  # Online location of your book
  #path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://github.com/Andreas-Siemens/matplotlib-templates.git
html:
#  use_issues_button: true
  use_repository_button: true
